name: Release

on:
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

jobs:
    release:
        runs-on: ubuntu-latest
        outputs:
            release_created: ${{ steps.release.outputs.release_created }}
            tag_name: ${{ steps.release.outputs.tag_name }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Release Please
              uses: googleapis/release-please-action@v4
              id: release
              with:
                  config-file: .release-please-config.json
                  manifest-file: .release-please-manifest.json

    # Optional: Build and test when a release is created
    build-and-test:
        runs-on: ubuntu-latest
        needs: release
        if: needs.release.outputs.release_created
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Run tests
              run: npm test
